---
title: "NYT API Assignment"
author: "Ken Markus"
date: "April 3, 2016"
output: html_document
---
```{r include=FALSE}
rm(list=ls())

#install.packages("devtools")
#install.packages(c("RCurl", "XML")) 
#options(pkgType="source")
#setRepositories() # select Omegahat
#install.packages("RHTMLForms", repos = "http://www.omegahat.net/R", type = "source")
#devtools::install_github("hadley/tidyr")

library(tidyr)
library(dplyr)
library(XML)
library(stringr)
library(ggplot2)
library(RCurl)
library(RHTMLForms)
library(jsonlite)
```

Let's begin...

```{r}

#There was a website that provided an easy way to solve this:  #https://cran.r-project.org/web/packages/jsonlite/vignettes/json-apis.html

movie_key <- "&api-key=5a3daaeee6bbc6b9df16284bc575e5ba:0:68700045"
url <- "http://api.nytimes.com/svc/movies/v2/reviews/dvd-picks.json?order=by-date"
req <- fromJSON(paste0(url, movie_key))
reviews <- req$results
colnames(reviews)

#Trying from the book examples...
movies_url <- "http://api.nytimes.com/svc/movies/v2/reviews/all.json?"
movie_api_key <- "api-key=4dc9125b801078f21f05dc266004dd0b:10:70565360"
critics_pick <- "critics-pick=Y"
order <- "order=by-date"
req <- str_c(movies_url,critics_pick,movie_api_key, order, sep = "&")
movies_json <- fromJSON(req)
movies.df <- movies_json$results
movies.df <- movies.df %>% select(display_title,publication_date,summary_short)
knitr::kable(movies.df)

#Let's just do one more query of movie reviews by the Coen Brothers
query <- "query=Coen"
req <- str_c(movies_url,critics_pick,movie_api_key, query, order, sep = "&")
movies_json <- fromJSON(req)
movies.df <- movies_json$results
movies.df <- movies.df %>% select(display_title,publication_date,summary_short)
knitr::kable(movies.df)
```
